In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import SVC

In [11]:
df=pd.read_csv('spam.csv')
df.head()

Label                                          EmailText
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [12]:
# data exploration
df.groupby('Label').describe()

EmailText                                                               
          count unique                                                top freq
Label                                                                         
ham        4825   4516                             Sorry, I'll call later   30
spam        747    653  Please call our customer service representativ...    4

In [13]:
# # convert label and message all to numbers
df['Label'].replace(['spam','ham'],[1,0],inplace=True)
df.head()

Label                                          EmailText
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Label      5572 non-null   int64 
 1   EmailText  5572 non-null   object
dtypes: int64(1), object(1)
memory usage: 87.2+ KB


In [26]:
# X=df['EmailText']
Y=df['Label']

In [30]:
Y.values
print(Y.shape)

(5572,)


In [31]:
# convert the message in the emails to numbers 
# countvectoriser
Vectoriser = CountVectorizer()
X = Vectoriser.fit_transform(df['EmailText'])
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [32]:
# # Split the training data 
# # X and Y is given by the email text and spam
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [33]:
X_train.shape

(4457, 8679)

In [34]:
Y_train.shape

(4457,)

In [35]:
model = SVC(kernel='rbf',gamma='scale',C=1)
model.fit(X_train,Y_train)

SVC(C=1)

In [36]:
model.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [38]:
# test the performance of my classifier
model.score(X_test,Y_test)

0.9874439461883409